openapi: 3.0.1
info: 
  title: SailPoint SaaS API
  version: 3.1.0-beta-internal
  description: >-
    ## API Usage and Support


    ![Beta](/api-beta.png)


    Unless otherwise indicated, calling any API endpoint described herein requires an OAuth2 Bearer token (JWT). See
    [Best Practices: IdentityNow REST API Authentication](https://community.sailpoint.com/t5/IdentityNow-Wiki/Best-Practices-IdentityNow-REST-API-Authentication/ta-p/79566).
tags:
  - name: Access Request Approvals
  - name: Auth Org Configuration
    description: Configurations for authentication and authorization
  - name: DataPipeline
  - name: IAIConfiguration
  - name: Internal Use Only
  - name: Notifications
  - name: Rosetta message handling
  - name: SP-Scheduler
  - name: SOD Policy
  - name: Triggers

components:
  securitySchemes:
    bearerAuth:
      $ref: './securitySchemes/OAuth2.yaml'

paths:
  /connector/clusters/{clusterId}/messages/{messageType}/invoke:
    $ref: './paths/beta/connector-messages.yaml'
  /assign-verified-from-addresses:
    $ref: './paths/beta/assign-verified-from-addresses.yaml'
  /auth-org-configuration:
    $ref: './paths/beta/auth-org-config.yaml'
  /email-requests:
    $ref: './paths/beta/email-requests.yaml'
  /non-employee-sources/{sourceId}/aggregate:
    $ref: './paths/beta/non-employee-source-aggregate.yaml'
  /iai-configurations:
    $ref: './paths/beta/iai-configurations.yaml'
  /iai-configurations/{type}:
    $ref: './paths/beta/iai-configuration.yaml'
  /trigger-subscriptions:
    $ref: './paths/beta/trigger-subscriptions-internal.yaml'
  /trigger-invocations/start:
    $ref: './paths/beta/trigger-invocations-start.yaml'
  /trigger-invocations:
    $ref: './paths/beta/trigger-invocations.yaml'
  /trigger-invocations/pending-events:
    $ref: './paths/beta/trigger-invocations-pending-events.yaml'
  /access-profiles/cleanup:
    $ref: './paths/beta/access-profiles-cleanup.yaml'
  /scheduled-actions:
    $ref: './paths/beta/scheduled-actions.yaml'
  /scheduled-actions/{id}:
    $ref: './paths/beta/scheduled-actions-delete.yaml'
  /scheduled-actions/bulk-delete:
    $ref: './paths/beta/scheduled-actions-bulk-delete.yaml'
  /access-request-approvals/pending:
    $ref: './paths/beta/pending-access-request-approvals.yaml'
  /access-request-approvals/completed:
    $ref: './paths/beta/completed-access-request-approvals.yaml'
  /access-request-approvals/{approvalId}/approve:
    $ref: './paths/beta/approve-access-request-approval.yaml'
  /access-request-approvals/{approvalId}/reject:
    $ref: './paths/beta/reject-access-request-approval.yaml'
  /access-request-approvals/{approvalId}/forward:
    $ref: './paths/beta/forward-access-request-approval.yaml'
  /access-request-approvals/approval-summary:
    $ref: './paths/beta/access-request-approval-summary.yaml'
  /sod-policies:
    $ref: './paths/beta/sod-policies.yaml'
  /sod-policies/{id}:
    $ref: './paths/beta/sod-policy.yaml'
  /sod-policies/{id}/schedule:
    $ref: './paths/beta/sod-schedule.yaml'
  /sod-policies/{id}/violation-report/run:
    $ref: './paths/beta/sod-report-run.yaml'
  /sod-policies/{id}/violation-report:
    $ref: './paths/beta/sod-violation-report.yaml'
  /sod-violation-report-status/{reportResultId}:
    $ref: './paths/beta/sod-violation-report-status.yaml'
  /sod-violation-report/run:
    $ref: './paths/beta/sod-all-report-run.yaml'
  /sod-violation-report:
    $ref: './paths/beta/sod-all-report-status.yaml'
  /sod-violation-report/{reportResultId}/download:
    $ref: './paths/beta/sod-download-default-report.yaml'
  /sod-violation-report/{reportResultId}/download/{fileName}:
    $ref: './paths/beta/sod-download-custom-report.yaml'
  /data-pipelines:
    $ref: './paths/beta/data-pipelines.yaml'
  /data-pipelines/{type}/dags/{id}/run:
    $ref: './paths/beta/run-datapipeline-dagid.yaml'
  /data-pipelines/{type}/run-latest:
    $ref: './paths/beta/run-datapipeline-dagtype.yaml'
  /entitlements-v3/identities/{identityId}/entitlements:
    $ref: './paths/beta/ears-identity-entitlement.yaml'
