openapi: 3.0.1
info:
  title: SailPoint SaaS API
  version: 2.0.0
components:
  securitySchemes:
    bearerAuth:
      $ref: './securitySchemes/OAuth2.yaml'
tags:
  - name: access-profiles
  - name: access-requests
  - name: accounts
  - name: approvals
  - name: identities
  - name: launchers
  - name: org
  - name: provisioning-activities
  - name: search
  - name: task-results
paths:
  '/access-profiles':
    $ref: './paths/v2/AccessProfiles.yaml'
  '/access-profiles/{accessProfileId}':
    $ref: './paths/v2/AccessProfileId.yaml'
  '/access-profiles/{accessProfileId}/entitlements':
    $ref: './paths/v2/AccessProfileEntitlements.yaml'
  '/access-requests':
    $ref: './paths/v2/AccessRequests.yaml'
  '/accounts':
    $ref: './paths/v2/Accounts.yaml'
  '/accounts/{id}':
    $ref: './paths/v2/AccountsWithId.yaml'
  '/approvals':
    $ref: './paths/v2/approvals/ApprovalsList.yaml'
  '/approvals/{approvalId}/approve-request':
      $ref: './paths/v2/approvals/ApproveRequest.yaml'
  '/approvals/{approvalId}/forward':
      $ref: './paths/v2/approvals/Forward.yaml'
  '/approvals/{approvalId}/reject-request':
      $ref: './paths/v2/approvals/RejectRequest.yaml'
  '/identities':
    $ref: './paths/v2/identities/Identities.yaml'
  '/identities/{identityIdOrAlias}':
    $ref: './paths/v2/identities/IdentityIdOrAlias.yaml'
  '/identities/{identityIdOrAlias}/approvals':
    $ref: './paths/v2/identities/IdentityIdOrAliasApprovals.yaml'
  '/identities/{identityIdOrAlias}/apps':
    $ref: './paths/v2/identities/IdentityIdOrAliasApps.yaml'
  '/identities/{identityIdOrAlias}/launchers':
    $ref: './paths/v2/identities/IdentityIdOrAliasLaunchers.yaml'
  '/identities/{identityIdOrAlias}/launchers/{launcherId}':
    $ref: './paths/v2/identities/LauncherId.yaml'
  '/identities/bulk-lock':
    $ref: './paths/v2/identities/IdentitiesBulkLock.yaml'
  '/launchers/{launcherId}':
      $ref: './paths/v2/launchers/LauncherId.yaml'
  '/launchers/{launcherId}/click':
      $ref: './paths/v2/launchers/Click.yaml'
  '/org':
    $ref: './paths/v2/Orgs.yaml'
  '/provisioning-activities':
    $ref: './paths/v2/provisioning-activities/ProvisioningActivitiesList.yaml'
  '/provisioning-activities/{provisioningActivityId}':
      $ref: './paths/v2/provisioning-activities/GetProvisioningActivity.yaml'
  '/search':
    $ref: './paths/v2/Search.yaml'
  '/search/runExport':
     "$ref": './paths/v2/search/RunExport.yaml'
  '/search/identities':
    "$ref": './paths/v2/search/Identities.yaml'
  '/search/identities/runExport':
    "$ref": './paths/v2/search/IdentitiesRunExport.yaml'
  '/search/entitlements':
    "$ref": './paths/v2/search/Entitlements.yaml'
  '/search/entitlements/runExport':
    "$ref": './paths/v2/search/EntitlementsRunExport.yaml'
  '/search/events':
    "$ref": './paths/v2/search/Events.yaml'
  '/search/mappings':
    "$ref": './paths/v2/search/Mappings.yaml'
  '/search/{index}/mappings':
    "$ref": './paths/v2/search/IndexMappings.yaml'
  '/task-results/{taskResultIdOrName}':
    $ref: './paths/v2/TaskResultIdOrName.yaml'

