type: object
properties:
  id:
    type: string
  name:
    type: string
  description:
    type: string
  dateCreated:
    type: string
    format: date-time
  lastUpdated:
    type: string
    format: date-time
  icon:
    type: string
  accessMethods:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        href:
          type: string
        method:
          type: string
        rel:
          type: string
          enum:
            - LAUNCHER
            - REQUEST
        status:
          type: string
