type: object
properties:
  daysTillEscalation:
    type: integer
  daysBetweenReminders:
    type: integer
  maxReminders:
    type: integer
  fallbackApprover:
    type: string
required:
  - daysTillEscalation
  - daysBetweenReminders
  - maxReminders
  - fallbackApprover
