openapi: 3.0.1
info:
  title: SailPoint SaaS API
  version: 3.1.0-beta-internal
  description: >-
    ## API Usage and Support


    ![Beta](/api-beta.png)


    Unless otherwise indicated, calling any API endpoint described herein requires an OAuth2 Bearer token (JWT). See
    [Best Practices: IdentityNow REST API Authentication](https://community.sailpoint.com/t5/IdentityNow-Wiki/Best-Practices-IdentityNow-REST-API-Authentication/ta-p/79566).
tags:
  - name: Access Request Recommendations
  - name: Attribute Synchronization
  - name: Auth Org Configuration
    description: Configurations for authentication and authorization
  - name: Auth User
    description: Authentication service user retrieval and update
  - name: Auth Support Login
    description: Support and Services Login to Customer Org
  - name: Auth MFA
    description: Multi-factor authentication with TOTP code during login
  - name: Authorization Model
    description: Capabilities and Rights for the Authorization Model Service
  - name: Certifications
  - name: Certification Campaigns
  - name: Entitlements
  - name: Forgot Username
  - name: IAI Common Access
  - name: IAI Data Pipeline
    description: Overall status for IAI Data Pipeline
  - name: IAI Data Pipeline Events
    description: Events Related to the IAI Data Pipeline
  - name: IAI Data Roles
    description: Information for role insights
  - name: IAI Configuration
    description: Configurations for IAI customers
  - name: IAI Outliers
    description: Identities classified as outliers by IAI
  - name: Identities
  - name: Identity Profiles
  - name: Internal Use Only
  - name: Lifecycle States
  - name: Managed Clients
    description: Read and write operations for managing client data
  - name: Notifications
  - name: Rosetta message handling
  - name: S3 Access
    description: Facilitates retrieving artifacts from S3 acting as a proxy endpoint to the caller.
  - name: SaaS Management
  - name: SOD Policy
  - name: SOD Exception
  - name: Sources
  - name: SP-Scheduler
  - name: Tags
    description: Operations on Tags
  - name: Task Management
    description: Operations on TaskDefinition, TaskInvocation and TaskStatus
  - name: Triggers
  - name: Password

components:
  securitySchemes:
    http:
      type: http
      scheme: bearer
      bearerFormat: JWT
    bearerAuth:
      $ref: './beta/securitySchemes/OAuth2.yaml'

paths:
  /sod-risks/risks/{id}:
    $ref: './beta/paths/sod/arm-risk.yaml'
  /access-request-recommendations:
    $ref: './beta/paths/rats-access-request-recommendations.yaml'
  /access-roles/change-segment-assignments:
    $ref: './beta/paths/access-roles-change-segment-assignments.yaml'
  /assign-verified-from-addresses:
    $ref: './beta/paths/assign-verified-from-addresses.yaml'
  /attribute-sync-config:
    $ref: './beta/paths/attr-sync-config-tenant.yaml'
  /auth-config-service/auth-config-v3/auth-org:
    $ref: './beta/paths/auth-org-config.yaml'
  /auth-config-service/auth-config-v3/auth-org/lockout-config:
    $ref: './beta/paths/auth-org-lockout-config.yaml'
  /auth-config-service/auth-config-v3/auth-org/network-config:
    $ref: './beta/paths/auth-org-network-config.yaml'
  /auth-config-service/auth-config-v3/auth-org/service-provider-config:
    $ref: './beta/paths/auth-org-service-provider-config.yaml'
  /auth-config-service/auth-config-v3/auth-org/session-config:
    $ref: './beta/paths/auth-org-session-config.yaml'
  /auth-config-service/auth-config-v3/auth-support-tenants:
    $ref: './beta/paths/supportlogin/auth-support-tenants.yaml'
  /auth-config-service/auth-config-v3/auth-support-logins:
    $ref: './beta/paths/supportlogin/auth-support-logins.yaml'
  /auth-config-service/auth-config-v3/auth-support-logins/{authTenant}:
    $ref: './beta/paths/supportlogin/auth-support-login.yaml'
  /auth-config-service/auth-config-v3/auth-support-logins/{oldAuthTenant}/migrate:
    $ref: './beta/paths/supportlogin/auth-support-logins-migrate.yaml'
  /auth-config-service/auth-config-v3/auth-support-login-granters:
    $ref: './beta/paths/supportlogin/access-granter-support-login-list.yaml'
  /auth-config-service/auth-config-v3/auth-support-login-granters/{accessGranterTenant}:
    $ref: './beta/paths/supportlogin/access-granter-support-login-get.yaml'
  /auth-config-service/auth-config-v3/auth-support-login-transfers:
    $ref: './beta/paths/supportlogin/auth-support-login-transfers-list.yaml'
  /auth-config-service/auth-config-v3/auth-support-login-transfers/{tenant}:
    $ref: './beta/paths/supportlogin/auth-support-login-transfer.yaml'
  /auth-config-service/auth-config-v3/auth-support-user-eligibility:
    $ref: './beta/paths/supportlogin/auth-support-user-eligibility-get.yaml'
  /oathkeeper/auth-mfa/token:
    $ref: './beta/paths/authmfa/generate-mfa-token.yaml'
  /sp-mfa/sp-mfa-v3/totp/generate-secret:
    $ref: './beta/paths/authmfa/generate-secret.yaml'
  /sp-mfa/sp-mfa-v3/totp/confirm-registration:
    $ref: './beta/paths/authmfa/confirm-registration.yaml'
  /sp-mfa/sp-mfa-v3/totp/verify-code:
    $ref: './beta/paths/authmfa/verify-code.yaml'
  /sp-mfa/sp-mfa-v3/registration-status/{externalId}:
    $ref: './beta/paths/authmfa/registration-status.yaml'
  /sp-mfa/sp-mfa-v3/mfa-registration/reset:
    $ref: './beta/paths/authmfa/mfa-registration-reset.yaml'
  /auth-users/{id}:
    $ref: './beta/paths/auth-user.yaml'
  /auth-users/{id}/password:
      $ref: './beta/paths/auth-user-password.yaml'
  /auth-users/bulk-update:
    $ref: './beta/paths/bulk-update-auth-user.yaml'
  /authorization/authorization-capabilities:
    $ref: './beta/paths/authorization-capabilities.yaml'
  /certification-tasks/{id}:
    $ref: './beta/paths/certification-task.yaml'
  /certification-tasks:
    $ref: './beta/paths/certification-tasks.yaml'
  /campaigns/{id}/reassign:
    $ref: './beta/paths/campaign-admin-cert-reassign.yaml'
  /certifications:
    $ref: './beta/paths/certifications.yaml'
  /certifications/{id}:
    $ref: './beta/paths/certification.yaml'
  /certifications/{id}/decide:
    $ref: './beta/paths/certifications-decide.yaml'
  /certifications/{id}/reassign:
    $ref: './beta/paths/certifications-reassign.yaml'
  /certifications/{id}/reassign-async:
    $ref: './beta/paths/certifications-reassign-async.yaml'
  /certifications/{id}/sign-off:
    $ref: './beta/paths/certifications-sign-off.yaml'
  /certifications/{id}/review-items:
    $ref: './beta/paths/certifications-review-items.yaml'
  /certifications/{id}/review-items-activity/{activityDataId}:
    $ref: './beta/paths/certifications-review-items-activity.yaml'
  /certifications/{id}/review-items/{itemId}/entitlements/{entitlementId}/permissions:
    $ref: './beta/paths/certifications-entitlement-permissions.yaml'
  /certifications/{id}/decision-summary:
    $ref: './beta/paths/certifications-decision-summary.yaml'
  /certifications/{id}/access-summaries/{type}:
    $ref: './beta/paths/certifications-access-summaries.yaml'
  /certifications/{id}/target-summaries:
    $ref: './beta/paths/certifications-target-summaries.yaml'
  /certifications/{id}/target-summary/{targetSummaryId}:
    $ref: './beta/paths/certifications-target-summary.yaml'
  /common-access/classify:
    $ref: './beta/paths/common-access-classify.yaml'
  /common-access/classify/{id}:
    $ref: './beta/paths/common-access-classify-request.yaml'
  /connector/clusters/{clusterId}/messages/{messageType}/invoke:
    $ref: './beta/paths/connector-messages.yaml'
  /email-requests:
    $ref: './beta/paths/email-requests.yaml'
  /entitlements-v3/entitlements:
    $ref: './beta/paths/entitlements.yaml'
  /forgot-username:
    $ref: './beta/paths/auth.yaml'
  /iai-roles:
    $ref: './beta/paths/iai-data-roles.yaml'
  /iai-roles/{roleId}/identities:
    $ref: './beta/paths/iai-data-role-entitlement-identities.yaml'
  /iai-roles/{roleId}/identities-entitlements:
    $ref: './beta/paths/iai-data-role-identities-entitlements.yaml'
  /iai-roles/{roleId}/entitlements:
    $ref: './beta/paths/iai-data-role-entitlements.yaml'
  /identities/{identityId}:
    $ref: './beta/paths/identity.yaml'
  /identities/{identity-id}/set-lifecycle-state:
    $ref: './beta/paths/identity-set-lifecycle-state.yaml'
  /identities/{identityId}/team:
    $ref: './beta/paths/identity-team.yaml'
  /identities/{identityId}/system-account:
    $ref: './beta/paths/system-accounts.yaml'
  /identities/{identityId}/synchronize-attributes:
    $ref: './beta/paths/identity-synchronize-attributes.yaml'
  /identity-groups:
    $ref: './beta/paths/identity-groups.yaml'
  /identity-groups/{identityGroupId}:
    $ref: './beta/paths/identity-group.yaml'
  /identity-groups/{identityGroupId}/identity-distribution:
    $ref: './beta/paths/identity-group-distribution.yaml'
  /identity-groups/{identityGroupId}/applications:
    $ref: './beta/paths/identity-group-applications.yaml'
  /identity-groups/{identityGroupId}/identities:
    $ref: './beta/paths/identity-group-identities.yaml'
  /identity-groups/{identityGroupId}/entitlement-popularities:
    $ref: './beta/paths/identity-group-entitlement-popularities.yaml'
  /identity-profiles:
    $ref: './beta/paths/identity-profiles.yaml'
  /identity-profiles/{id}:
    $ref: './beta/paths/identity-profiles-id.yaml'
  /identity-profiles/bulk-delete:
    $ref: './beta/paths/identity-profiles-bulk-delete.yaml'
  /identity-profiles/identity-preview:
    $ref: './beta/paths/identity-profiles-identity-preview.yaml'
  /identity-profiles/{identity-profile-id}:
    $ref: './beta/paths/identity-profile.yaml'
  /identity-profiles/{identity-profile-id}/default-identity-attribute-config:
    $ref: './beta/paths/identity-profile-default-config.yaml'
  /identity-profiles/{identity-profile-id}/lifecycle-states:
    $ref: './beta/paths/lifecycle-states.yaml'
  /identity-profiles/{identity-profile-id}/lifecycle-states/{lifecycle-state-id}:
    $ref: './beta/paths/delete-lifecycle-state.yaml'
  /identity-profiles/{identity-profile-id}/refresh-identities:
    $ref: './beta/paths/identity-profile-refresh-identities.yaml'
  /managed-clients:
    $ref: './beta/paths/managed-clients.yaml'
  /managed-clients/{id}:
    $ref: './beta/paths/managed-clients-path.yaml'
  /managed-clients/{id}/request-credentials:
    $ref: "./beta/paths/managed-clients-credentials.yaml"
  /managed-clusters/{id}/jobs:
    $ref: './beta/paths/managed-cluster-jobs.yaml'
  /managed-clusters/{id}/process-config:
    $ref: './beta/paths/managed-cluster-processes.yaml'
  /managed-clusters/{id}/upgrade:
    $ref: './beta/paths/managed-cluster-upgrade.yaml'
  /managed-cluster-types/:
    $ref: './beta/paths/managed-cluster-types.yaml'
  /managed-cluster-types/{id}:
    $ref: './beta/paths/managed-cluster-types-path.yaml'
  /managed-processes/:
    $ref: './beta/paths/managed-processes.yaml'
  /managed-processes/{id}:
    $ref: './beta/paths/managed-processes-path.yaml'
  /managed-clusters/{id}:
    $ref: './beta/paths/managed-cluster-path-internal.yaml'
  /managed-clusters:
    $ref: './beta/paths/managed-clusters-create.yaml'
  /managed-clusters/{id}/status:
    $ref: './beta/paths/managed-cluster-status.yaml'
  /managed-clusters/cache:
    $ref: './beta/paths/managed-cluster-cache.yaml'
  /managed-clusters/{id}/set-encryption-keys:
    $ref: './beta/paths/managed-clusters-set-encryption-keys.yaml'
  /non-employee-sources/{sourceId}/aggregate:
    $ref: './beta/paths/non-employee-source-aggregate.yaml'
  /bulk-outlier-detection:
    $ref: './beta/paths/outliers-bulk-outlier-detection.yaml'
  /iai-configurations:
    $ref: './beta/paths/iai-configurations.yaml'
  /iai-configurations/{type}:
    $ref: './beta/paths/iai-configuration.yaml'
  /segments/{id}/change-assignments:
    $ref: './beta/paths/segment-change-assignments.yaml'
  /sources/{id}/attribute-sync-config:
    $ref: './beta/paths/attr-sync-config-source.yaml'
  /sources/{id}/synchronize-attributes:
    $ref: './beta/paths/source-synchronize-attributes.yaml'
  /sources/{id}/update-aggregation-state:
    $ref: './beta/paths/source-aggregation-state.yaml'
  /non-employee-sources/{id}/non-employee-bulk-upload/details:
    $ref: './beta/paths/non-employee-sources-bulk-upload-details.yaml'
  /non-employee-bulk-upload-job/{bulkUploadJobId}/fail:
    $ref: './beta/paths/non-employee-bulk-upload-jobs-fail.yaml'
  /trigger-subscriptions:
    $ref: './beta/paths/trigger-subscriptions-internal.yaml'
  /trigger-invocations/start:
    $ref: './beta/paths/trigger-invocations-start.yaml'
  /trigger-invocations:
    $ref: './beta/paths/trigger-invocations.yaml'
  /trigger-invocations/pending-events:
    $ref: './beta/paths/trigger-invocations-pending-events.yaml'
  /access-profiles/cleanup:
    $ref: './beta/paths/access-profiles-cleanup.yaml'
  /scheduled-actions:
    $ref: './beta/paths/scheduled-actions.yaml'
  /scheduled-actions/{id}:
    $ref: './beta/paths/scheduled-actions-delete.yaml'
  /scheduled-actions/bulk-delete:
    $ref: './beta/paths/scheduled-actions-bulk-delete.yaml'
  /data-pipelines:
    $ref: './beta/paths/data-pipelines.yaml'
  /data-pipelines/{type}/dags/{id}/run:
    $ref: './beta/paths/run-datapipeline-dagid.yaml'
  /data-pipelines/{type}/run-latest:
    $ref: './beta/paths/run-datapipeline-dagtype.yaml'
  /data-pipeline-events:
    $ref: './beta/paths/data-pipeline-events.yaml'
  /data-pipeline-events/{qualifier}:
    $ref: './beta/paths/data-pipeline-events-qualifier.yaml'
  /data-pipeline-events/{qualifier}/related:
    $ref: './beta/paths/data-pipeline-events-qualifier-related.yaml'
  /entitlements-v3/identities/{id}/entitlements:
    $ref: './beta/paths/ears-identity-entitlement.yaml'
  /entitlements-v3/entitlements/{id}/parents:
    $ref: './beta/paths/ears-entitlement-parents.yaml'
  /entitlements-v3/entitlements/{id}/children:
    $ref: './beta/paths/ears-entitlement-children.yaml'
  /entitlements-v3/entitlements/bulk-update:
    $ref: './beta/paths/ears-entitlement-bulk-update.yaml'
  /s3-proxy:
    $ref: './beta/paths/s3-proxy.yaml'
  /saas-management/applications:
    $ref: './beta/paths/saas-management-applications.yaml'
  /saas-management/applications/source/{id}:
    $ref: './beta/paths/saas-management-application-for-source.yaml'
  /saas-management/applications/update-map:
    $ref: './beta/paths/saas-management-applications-update-map.yaml'
  /saas-management/applications/source/{id}/test:
    $ref: './beta/paths/saas-management-applications-test.yaml'
  /sod-violations/check:
    $ref: './beta/paths/sod-violation-check.yaml'
  /sod-exceptions:
    $ref: './beta/paths/sod-exceptions.yaml'
  /sod-exceptions/{id}:
    $ref: './beta/paths/sod-exception.yaml'
  /sod-exceptions/bulk-create:
    $ref: './beta/paths/sod-exceptions-bulk-create.yaml'
  /sources/{id}/schemas/accounts:
    $ref: './beta/paths/source-accounts-schema.yaml'
  /sources/{id}/schemas/entitlements:
    $ref: './beta/paths/source-entitlements-schema.yaml'
  /sources/{id}/update-connector-state:
    $ref: './beta/paths/source-connector-state.yaml'
  /sources/{sourceId}/upload-connector-file:
    $ref: './beta/paths/source-upload-connector-file.yaml'
  /sources/{sourceId}/connector/extract/{messageType}:
    $ref: './beta/paths/source-connector-initiate-extract.yaml'
  /task-definitions:
    $ref: './beta/paths/task-definitions.yaml'
  /task-definitions/{id}:
    $ref: './beta/paths/task-definition.yaml'
  /task-execution/run:
    $ref: './beta/paths/task-execution-run.yaml'
  /task-execution/{id}/cancel:
    $ref: './beta/paths/task-execution-cancel.yaml'
  /task-status/{id}:
    $ref: './beta/paths/task-status.yaml'
  /task-status/pending-tasks:
    $ref: './beta/paths/task-status-pending.yaml'
  /password-v3/password-sync-groups:
    $ref: './beta/paths/internal-password-sync-groups.yaml'
  /roles/identity/{id}/roles:
    $ref: './beta/paths/roles-by-identity.yaml'
  /tags:
    $ref: './beta/paths/tags.yaml'
  /tags/{id}:
    $ref: './beta/paths/tag.yaml'
  /tags/bulk-get:
    $ref: './beta/paths/tags-get-shared.yaml'