#
# Copyright (C) 2021 SailPoint Technologies, Inc.  All rights reserved.
#
openapi: 3.0.0
info:
  title: Managed Cluster Types API
  description: This is an API for accessing and managing Cluster type information (IDN/IAI/etc).
  contact:
    email: scrum-denali@sailpoint.com
  version: 1.0.0-oas3
  x-copyright-year: 2021
servers:
  - url: http://localhost:7100/v3/
tags:
  - name: Managed Cluster Types
    description: Operations for accessing and managing Cluster type information (IDN/IAI/etc).
paths:
  /managed-cluster-types:
    $ref: '../beta/paths/managed-cluster-types.yaml'
  /managed-cluster-types/{id}:
    $ref: '../beta/paths/managed-cluster-types-path.yaml'


components:
  securitySchemes:
    bearerAuth:
      type: oauth2
      description: This API uses OAuth 2 with the client credentials grant flow.
      flows:
        clientCredentials:
          tokenUrl: https://acme-solar.api.cloud.sailpoint.com/oauth/token
          scopes:
            idn:managed-cluster-types:create: ManagedClusterType create access
            idn:managed-cluster-types:read: ManagedClusterType read access
            idn:managed-cluster-types:update: ManagedClusterType update access
            idn:managed-cluster-types:delete: ManagedClusterType delete access
