#
# Copyright (C) 2021 SailPoint Technologies, Inc.  All rights reserved.
#
openapi: 3.0.0
info:
  title: Managed Processes API
  description: This is an API for accessing and managing Cluster upgrade process information.
  contact:
    email: scrum-denali@sailpoint.com
  version: 1.0.0-oas3
  x-copyright-year: 2021
servers:
  - url: http://localhost:7100/v3/
tags:
  - name: Managed Processes
    description: Operations for accessing and managing Cluster upgrade process information
paths:
  /managed-processes:
    $ref: '../beta/paths/managed-processes.yaml'
  /managed-processes/{id}:
    $ref: '../beta/paths/managed-processes-path.yaml'


components:
  securitySchemes:
    bearerAuth:
      type: oauth2
      description: This API uses OAuth 2 with the client credentials grant flow.
      flows:
        clientCredentials:
          tokenUrl: https://acme-solar.api.cloud.sailpoint.com/oauth/token
          scopes:
            idn:managed-process:create: ManagedProcess create access
            idn:managed-process:read: ManagedProcess read access
            idn:managed-process:update: ManagedProcess update access
            idn:managed-process:delete: ManagedProcess delete access
